In [1]:
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
import seaborn as sns

/home/turpindominique/.pyenv/versions/convertiq/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
file_path = "2019-Oct.csv"

# Loading dataset with pandas kwargs
df = kagglehub.load_dataset(
KaggleDatasetAdapter.PANDAS,
"mkechinov/ecommerce-behavior-data-from-multi-category-store",
file_path,
pandas_kwargs={
"nrows": 5_000_000, # choosing just the enough rows
"dtype": {'event_type': 'category',
       'product_id': 'int32',
       'category_code': 'category',
       'brand': 'category',
       'price': 'float32',
       'user_id': 'int32',
       }},

)

/tmp/ipykernel_18662/2238151501.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

In [3]:
pd.options.display.max_rows = 999

In [4]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.790001,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.200001,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.099976,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.740005,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.979980,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [5]:
df['user_session'].value_counts()

user_session
fb075266-182d-4c11-b5f7-4e4dcdabd4a7    614
e867404d-f9dc-46b1-b484-427eaa9fabff    355
0deca816-5a12-45d8-8474-d28c2b6dda06    326
0b9e217e-1286-40ae-9687-14d8ddab276e    311
4c8fbbcd-84d6-475f-8f25-0aa063707e4a    275
                                       ...
70fcbe66-784d-418b-832c-995a5ae8fdef      1
25fe1880-d17b-41d7-9406-ef68a20b3c77      1
10e11040-41ce-4d88-93e7-976489433daa      1
43864f48-4e22-408c-b1ec-e44734c7463e      1
c3803a39-8e7b-4f92-9664-b9126c7e9579      1
Name: count, Length: 1072339, dtype: int64

In [6]:
df.shape

(5000000, 9)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     category
 2   product_id     int32
 3   category_id    int64
 4   category_code  category
 5   brand          category
 6   price          float32
 7   user_id        int32
 8   user_session   object
dtypes: category(3), float32(1), int32(2), int64(1), object(2)
memory usage: 190.8+ MB

In [8]:
df['event_type'].value_counts(normalize=True)

event_type
view        0.963445
cart        0.019490
purchase    0.017064
Name: proportion, dtype: float64

Data question:
-If you go and check unique values and count the unique values in event_type - there are only view, cart, and purchase values - no "removed from cart" value as claimed in the dataset description?
Answer: Correct. Unfortunately, this specific retailer doesn't use remove_from_cart event. They are using override cart mechanics in API. So you can figured out removed from cart products as difference between purchase and cart events.
Source: https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/discussion/132470

In [9]:
df.isnull().sum()/df.shape[0]

event_time       0.000000
event_type       0.000000
product_id       0.000000
category_id      0.000000
category_code    0.310210
brand            0.139139
price            0.000000
user_id          0.000000
user_session     0.000000
dtype: float64

In [10]:
df.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.790001,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.200001,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.099976,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.740005,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.979980,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d
5,2019-10-01 00:00:05 UTC,view,1480613,2053013561092866779,computers.desktop,pulser,908.619995,512742880,0d0d91c2-c9c2-4e81-90a5-86594dec0db9
6,2019-10-01 00:00:08 UTC,view,17300353,2053013553853497655,NaN,creed,380.959991,555447699,4fe811e9-91de-46da-90c3-bbd87ed3a65d
7,2019-10-01 00:00:08 UTC,view,31500053,2053013558031024687,NaN,luminarc,41.160000,550978835,6280d577-25c8-4147-99a7-abc6048498d6
8,2019-10-01 00:00:10 UTC,view,28719074,2053013565480109009,apparel.shoes.keds,baden,102.709999,520571932,ac1cd4e5-a3ce-4224-a2d7-ff660a105880
9,2019-10-01 00:00:11 UTC,view,1004545,2053013555631882655,electronics.smartphone,huawei,566.010010,537918940,406c46ed-90a4-4787-a43b-59a410c1a5fb

In [11]:
df['category_code'].nunique()

123

In [12]:
df['product_id'].nunique()

104341

In [13]:
df['category_id'].nunique()

557

In [14]:
df['category_code'].nunique()

123

In [15]:
df[df['event_type']=='purchase']['user_id'].nunique()

53596

In [16]:
df[df['category_code']=='electronics.smartphone']['category_id'].value_counts()

category_id
2053013555631882655    1412334
Name: count, dtype: int64

In [17]:
df[df['category_code']=='appliances.environment.water_heater'].value_counts()

event_time               event_type  product_id  category_id          category_code                        brand       price       user_id    user_session
2019-10-03 09:07:40 UTC  cart        3900003     2053013552326770905  appliances.environment.water_heater  ariston     120.430000  532684809  54109a89-f6b5-4245-8f47-071bade06e27    3
2019-10-04 13:08:58 UTC  cart        3900776     2053013552326770905  appliances.environment.water_heater  artel       86.050003   539561104  34256b1e-85c0-4374-ba45-3876de45b1da    2
2019-10-04 07:52:21 UTC  cart        3900883     2053013552326770905  appliances.environment.water_heater  garanterm   97.790001   518691417  06405a22-b894-44a7-a297-1197d8fb6071    2
2019-10-03 09:07:41 UTC  cart        3900003     2053013552326770905  appliances.environment.water_heater  ariston     120.430000  532684809  54109a89-f6b5-4245-8f47-071bade06e27    2
2019-10-03 17:40:09 UTC  view        3900339     2053013552326770905  appliances.environment.water_heater  aqua        30.629999   533333642  3c422f62-aa55-4330-94ba-82fdb4265547    1
                                                                                                                                                                                     ..
2019-10-02 09:56:52 UTC  purchase    3900922     2053013552326770905  appliances.environment.water_heater  ariston     437.239990  524296558  041e970f-d321-4100-ab7e-9575b6696ac1    1
2019-10-02 09:55:32 UTC  view        3900922     2053013552326770905  appliances.environment.water_heater  ariston     437.239990  524296558  041e970f-d321-4100-ab7e-9575b6696ac1    1
2019-10-02 09:55:17 UTC  view        3900591     2053013552326770905  appliances.environment.water_heater  electrolux  154.419998  516445860  a61d60c7-bb4a-4c65-ad97-808a7f4118ab    1
2019-10-02 09:55:08 UTC  view        3900922     2053013552326770905  appliances.environment.water_heater  ariston     437.239990  524296558  041e970f-d321-4100-ab7e-9575b6696ac1    1
2019-10-02 09:58:48 UTC  view        3900815     2053013552326770905  appliances.environment.water_heater  ariston     133.809998  537222440  28dcf651-52e7-4dc0-aa3a-e94bb8556faf    1
Name: count, Length: 18588, dtype: int64

In [18]:
df[df['event_type']=='purchase'].value_counts()

event_time               event_type  product_id  category_id          category_code                      brand      price        user_id    user_session
2019-10-04 07:20:16 UTC  purchase    5700758     2053013553970938175  auto.accessories.player            pioneer    75.940002    517161433  80109315-6ff2-4b59-adec-f99cd75efb81    2
2019-10-01 12:42:40 UTC  purchase    1004767     2053013555631882655  electronics.smartphone             samsung    254.190002   512386086  4a1f199d-e77b-4ff7-8807-47b31c1b6aca    2
2019-10-01 06:41:39 UTC  purchase    1004856     2053013555631882655  electronics.smartphone             samsung    130.759995   555119233  53ad00ec-2d13-491c-9743-504913ea238c    2
2019-10-03 18:59:40 UTC  purchase    1003709     2053013555631882655  electronics.smartphone             samsung    715.020020   556497056  dcb2bab7-aba3-4d72-a6d7-68097e957777    1
2019-10-03 18:59:32 UTC  purchase    1005067     2053013555631882655  electronics.smartphone             samsung    1209.550049  530834332  c5f997d9-7294-4bf6-aecf-9546af72999e    1
                                                                                                                                                                                   ..
2019-10-02 09:39:42 UTC  purchase    5100577     2053013553341792533  electronics.clocks                 samsung    295.630005   518728748  1b8c76d3-4a42-4be2-b97e-e2d82d46bd10    1
2019-10-02 09:39:51 UTC  purchase    11300112    2053013555531219353  electronics.telephone              panasonic  36.529999    555155735  785e156c-d0e1-42ff-b346-917d811f2905    1
2019-10-02 09:39:52 UTC  purchase    1002544     2053013555631882655  electronics.smartphone             apple      462.660004   523309472  660f0b99-95fd-4c0b-b12c-0ce8ef810b97    1
2019-10-02 09:39:53 UTC  purchase    1004871     2053013555631882655  electronics.smartphone             samsung    286.670013   515937356  8353e4df-faaa-4cf8-b43c-a59bb11ce41d    1
2019-10-02 09:39:19 UTC  purchase    6200950     2053013552293216471  appliances.environment.air_heater  willmark   20.570000    513369545  02246b7d-8966-465f-ac2c-3873e1972690    1
Name: count, Length: 64835, dtype: int64

In [19]:
df_groupby = df.groupby('category_code')['event_type'].apply(lambda x: (x == 'purchase').sum())

/tmp/ipykernel_18662/1857955882.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_groupby = df.groupby('category_code')['event_type'].apply(lambda x: (x == 'purchase').sum())

In [20]:
df_groupby.sort_values(ascending=False)

category_code
electronics.smartphone                    40063
electronics.audio.headphone                3895
electronics.video.tv                       2465
electronics.clocks                         2253
computers.notebook                         2029
appliances.kitchen.washer                  1735
appliances.environment.vacuum              1387
appliances.kitchen.refrigerators           1111
auto.accessories.player                     621
electronics.tablet                          570
appliances.environment.air_heater           568
electronics.telephone                       452
electronics.audio.subwoofer                 437
appliances.iron                             415
appliances.kitchen.microwave                396
appliances.kitchen.blender                  369
appliances.environment.water_heater         368
computers.desktop                           362
appliances.kitchen.kettle                   341
kids.carriage                               319
appliances.kitchen.meat_grinder             317
apparel.shoes                               311
auto.accessories.alarm                      295
construction.tools.drill                    292
computers.peripherals.printer               276
auto.accessories.videoregister              269
appliances.kitchen.oven                     263
appliances.sewing_machine                   245
apparel.shoes.keds                          228
construction.tools.saw                      210
furniture.bedroom.bed                       193
furniture.living_room.cabinet               153
construction.tools.generator                148
accessories.bag                             142
computers.components.hdd                    136
appliances.kitchen.mixer                    133
appliances.personal.hair_cutter             132
electronics.audio.acoustic                  130
furniture.kitchen.chair                     128
computers.peripherals.mouse                 117
appliances.personal.scales                  116
construction.tools.welding                  114
computers.components.videocards             112
computers.peripherals.monitor               112
kids.toys                                   112
appliances.kitchen.hob                      104
kids.fmcg.diapers                           104
kids.skates                                 101
appliances.kitchen.hood                      96
furniture.living_room.sofa                   93
sport.bicycle                                89
appliances.kitchen.grill                     76
auto.accessories.compressor                  74
furniture.living_room.chair                  74
appliances.ironing_board                     70
computers.peripherals.keyboard               65
appliances.kitchen.dishwasher                65
furniture.kitchen.table                      64
appliances.kitchen.coffee_machine            62
computers.components.memory                  61
appliances.kitchen.toster                    56
appliances.kitchen.juicer                    56
appliances.environment.air_conditioner       49
construction.tools.pump                      45
electronics.camera.photo                     44
computers.components.cooler                  44
auto.accessories.radar                       43
kids.dolls                                   40
medicine.tools.tonometer                     37
kids.swing                                   37
construction.components.faucet               37
electronics.audio.microphone                 36
electronics.camera.video                     35
sport.trainer                                34
electronics.audio.music_tools.piano          33
computers.ebooks                             30
computers.components.motherboard             29
accessories.wallet                           24
computers.components.cpu                     22
furniture.bathroom.toilet                    21
computers.components.power_supply            21
furniture.bedroom.blanket                    18
furniture.bedroom.pillow                     17
construction.tools.light                     14
appliances.kitchen.coffee_grinder            13
appliances.personal.massager                 12
electronics.video.projector                  11
construction.tools.painting                  11
apparel.shoes.moccasins                      11
auto.accessories.parktronic                  11
apparel.costume                              10
furniture.universal.light                    10
country_yard.lawn_mower                       9
stationery.cartrige                           7
furniture.bathroom.bath                       7
appliances.kitchen.steam_cooker               7
apparel.tshirt                                6
apparel.trousers                              5
apparel.underwear                             5
computers.peripherals.camera                  5
accessories.umbrella                          4
country_yard.cultivator                       4
appliances.environment.fan                    4
apparel.shoes.slipons                         3
apparel.jeans                                 3
apparel.shirt                                 2
sport.ski                                     2
auto.accessories.winch                        1
apparel.sock                                  1
apparel.scarf                                 1
apparel.belt                                  1
sport.snowboard                               1
apparel.shoes.step_ins                        0
apparel.shoes.sandals                         0
apparel.skirt                                 0
apparel.dress                                 0
apparel.jacket                                0
apparel.shorts                                0
apparel.shoes.ballet_shoes                    0
apparel.shoes.espadrilles                     0
country_yard.furniture.bench                  0
country_yard.furniture.hammok                 0
sport.tennis                                  0
Name: event_type, dtype: int64

In [21]:
top5 = ['electronics.smartphone', 'electronics.audio.headphone', 'electronics.video.tv',
'electronics.clocks', 'computers.notebook']

X = df[df['category_code'].isin(top5)]

In [22]:
X.shape

(1993170, 9)

In [23]:
X[X['event_type']=='purchase'].shape

(50705, 9)

In [24]:
X.isnull().sum()/X.shape[0]

event_time       0.000000
event_type       0.000000
product_id       0.000000
category_id      0.000000
category_code    0.000000
brand            0.017736
price            0.000000
user_id          0.000000
user_session     0.000000
dtype: float64

In [25]:
X.duplicated().sort_values()

3          False
3346013    False
3346006    False
3346005    False
3345998    False
           ...
434226      True
3872026     True
3872024     True
3703560     True
4027760     True
Length: 1993170, dtype: bool

In [26]:
X_concat = (
    X.groupby(["user_id", "category_id", "product_id", "price"], as_index=False).
    agg({
        "event_type": " ".join,
        "event_time": " ".join,
        "user_session": " ".join,
        })
)

In [27]:
X_concat.head()

,user_id,category_id,product_id,price,event_type,event_time,user_session
0,241587569,2053013555631882655,1004857,130.250000,view,2019-10-02 11:28:14 UTC,8a09b6c6-07e6-4f80-ae22-a6b400fc7894
1,241784978,2053013555631882655,1002544,462.380005,view,2019-10-04 08:00:07 UTC,db17076d-5be1-4f1e-acd1-a2baf23eb3fd
2,244951053,2053013555631882655,1003535,460.500000,view view,2019-10-01 08:47:35 UTC 2019-10-01 08:48:28 UTC,91769fdf-461b-4e43-9c73-88a07481b75c 91769fdf-...
3,244951053,2053013555631882655,1004659,731.039978,view view,2019-10-03 03:07:42 UTC 2019-10-03 03:08:27 UTC,ac5e27ca-6408-47ab-9837-19893a0334c2 ac5e27ca-...
4,244951053,2053013555631882655,1005105,1415.479980,view,2019-10-03 03:06:18 UTC,ac5e27ca-6408-47ab-9837-19893a0334c2

In [28]:
X_concat['event_type'].value_counts()

event_type
view                                                                                        724274
view view                                                                                   234566
view view view                                                                               65679
view view view view                                                                          25172
view view view view view                                                                     10608
                                                                                             ...
view cart cart cart cart cart cart cart cart cart view cart purchase view                        1
view view cart cart cart cart cart cart cart cart cart cart cart cart cart cart purchase         1
view cart cart view view cart purchase view cart purchase view view                              1
view view view cart cart cart cart cart cart cart view cart cart purchase view                   1
view cart view cart view view cart purchase view cart purchase view view                         1
Name: count, Length: 6071, dtype: int64

In [29]:
X_concat.shape

(1137079, 7)